/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents (marketplace) */
        get: operations["list_agents_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent detail */
        get: operations["get_agent_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/nav-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NAV time series */
        get: operations["get_nav_history_agents__agent_id__nav_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent NAV vs sSPY and 60/40 baselines (synthetic constant growth) */
        get: operations["get_benchmark_agents__agent_id__benchmark_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluate mandate emergencyExitConditions against live CoinGecko market data */
        get: operations["get_conditions_agents__agent_id__conditions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision log (rebalance/harvest/distribute) */
        get: operations["list_agent_decisions_agents__agent_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/mint-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview shares received for a USDC mint amount (see ADR D002) */
        post: operations["mint_preview_agents__agent_id__mint_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/pyth-update-bytes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pyth update bytes needed for this agent's mint/burn TX (see ADR D001) */
        get: operations["pyth_update_bytes_agents__agent_id__pyth_update_bytes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mandate/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LLM mandate parse (NL → constrained JSON) */
        post: operations["parse_mandate_mandate_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mandate/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate hand-edited mandate (no LLM) */
        post: operations["validate_mandate_mandate_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-wallet portfolio aggregate */
        get: operations["get_portfolio_portfolio__address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/redemptions/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending redemption requests for a wallet */
        get: operations["get_redemptions_redemptions__address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain config + contract addresses + Pyth feeds */
        get: operations["system_info_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/time/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance TimeProvider clock (testnet only) */
        post: operations["admin_time_advance_admin_time_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mint-usdc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint MockUSDC to address (testnet only) */
        post: operations["admin_mint_usdc_admin_mint_usdc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{agent_id}/rebalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger rebalance for agent (testnet only) */
        post: operations["admin_rebalance_admin_agents__agent_id__rebalance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{agent_id}/harvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger harvest for agent (testnet only) */
        post: operations["admin_harvest_admin_agents__agent_id__harvest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{agent_id}/distribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger dividend distribute for agent (testnet only) */
        post: operations["admin_distribute_admin_agents__agent_id__distribute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{agent_id}/nft-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate NFT metadata + pin IPFS + setTokenURI (testnet only) */
        post: operations["admin_nft_metadata_admin_agents__agent_id__nft_metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/debug/indexer-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexer sync state vs current chain head */
        get: operations["debug_indexer_state_admin_debug_indexer_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/debug/agents/{agent_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare BE DB state vs live SC chain state for a single agent */
        get: operations["debug_agent_compare_admin_debug_agents__agent_id__compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/debug/synthetic-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Pyth-priced synthetic asset prices (USDC, 6-dec) */
        get: operations["debug_synthetic_prices_admin_debug_synthetic_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/debug/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** mETH / USDY adapter live state (exchange rates, simulated APY) */
        get: operations["debug_adapters_admin_debug_adapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/debug/treasury": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PlatformTreasury fee rates + cumulative fees collected */
        get: operations["debug_treasury_admin_debug_treasury_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/debug/agents/{agent_id}/founder-vault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live FounderVault SC state (deposits, carry, lockup, subordination) */
        get: operations["debug_founder_vault_admin_debug_agents__agent_id__founder_vault_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/debug/agents/{agent_id}/redemption-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live RedemptionQueue state for an agent (pending shares + tier allow-list) */
        get: operations["debug_redemption_queue_admin_debug_agents__agent_id__redemption_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents/{agent_id}/qualify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Phase-2 qualification criteria (read-only, testnet only) */
        get: operations["admin_qualify_check_admin_agents__agent_id__qualify_get"];
        put?: never;
        /** Evaluate qualification + auto-advance to PublicLaunch if passed */
        post: operations["admin_qualify_advance_admin_agents__agent_id__qualify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health (indexer, cron, LLM) */
        get: operations["system_health_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe (Railway / Docker / k8s)
         * @description Lightweight probe — DB SELECT 1 must succeed (HTTP 503 otherwise);
         *     chain RPC reachability is reported but non-fatal.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminDistributeResponse */
        AdminDistributeResponse: {
            /** Agentid */
            agentId: number;
            /** Amount */
            amount: string;
            /** Stagetxhash */
            stageTxHash?: string | null;
            /** Distributetxhash */
            distributeTxHash?: string | null;
            /** Note */
            note?: string | null;
        };
        /** AdminHarvestResponse */
        AdminHarvestResponse: {
            /** Agentid */
            agentId: number;
            /** Txhash */
            txHash: string;
        };
        /** AdminNftMetadataResponse */
        AdminNftMetadataResponse: {
            /** Agentid */
            agentId: number;
            /** Txhash */
            txHash: string;
            /** Uri */
            uri: string;
            /** Attributecount */
            attributeCount?: number | null;
        };
        /** AdminRebalanceResponse */
        AdminRebalanceResponse: {
            /** Agentid */
            agentId: number;
            /** Txhash */
            txHash: string;
            /** Targetweights */
            targetWeights: [
                string,
                number
            ][];
        };
        /** AgentDetail */
        AgentDetail: {
            /** Agentid */
            agentId: number;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
            /** Founderaddress */
            founderAddress: string;
            /** Vaultaddress */
            vaultAddress: string;
            /** Tokenaddress */
            tokenAddress: string;
            phase: components["schemas"]["AgentPhase"];
            /** Incubationstart */
            incubationStart: number;
            /** Publiclaunchat */
            publicLaunchAt?: number | null;
            /** Navusdc */
            navUsdc: string;
            /** Navpershareusdc */
            navPerShareUsdc: string;
            /** Totalshares */
            totalShares: string;
            /** Holdercount */
            holderCount: number;
            /** Apy30Dbps */
            apy30DBps?: number | null;
            /** Apy7Dbps */
            apy7DBps?: number | null;
            /** Reputation */
            reputation: number;
            /** Strategy */
            strategy: string;
            /** Assetclasses */
            assetClasses: components["schemas"]["AssetClass"][];
            /** Allowedlockups */
            allowedLockups: components["schemas"]["LockupTier"][];
            /** Thumbnailurl */
            thumbnailUrl?: string | null;
            /** Createdat */
            createdAt: number;
            performance?: components["schemas"]["AgentPerformance"] | null;
            /** Marketpricepershareusdc */
            marketPricePerShareUsdc?: string | null;
            /** Reputationpremiumbps */
            reputationPremiumBps?: number | null;
            mandate?: components["schemas"]["MandateSchema"] | null;
            /** Mandateuri */
            mandateUri: string;
            /** Mandatehash */
            mandateHash: string;
            /** Positions */
            positions: components["schemas"]["Position"][];
            /** Cashusdc */
            cashUsdc: string;
            /** Yieldpool */
            yieldPool: string;
            founderVault?: components["schemas"]["FounderVaultSnapshot"] | null;
            /** Recentdividends */
            recentDividends: components["schemas"]["DividendEpoch"][];
            /** Recentdecisions */
            recentDecisions: components["schemas"]["Decision"][];
            latestNarratorNote?: components["schemas"]["NarratorNote"] | null;
            redemptionQueue: components["schemas"]["RedemptionQueueSnapshot"];
            windDown?: components["schemas"]["WindDownState"] | null;
        };
        /** AgentPerformance */
        AgentPerformance: {
            /** Totalreturn */
            totalReturn?: number | null;
            /** Maxdrawdown */
            maxDrawdown?: number | null;
            /** Sharperatio */
            sharpeRatio?: number | null;
            /** Samplecount */
            sampleCount: number;
            /** Periodstart */
            periodStart?: number | null;
            /** Periodend */
            periodEnd?: number | null;
        };
        /**
         * AgentPhase
         * @enum {string}
         */
        AgentPhase: "Incubation" | "PublicLaunch" | "WindDown" | "Slashed" | "Settled";
        /** AgentSummary */
        AgentSummary: {
            /** Agentid */
            agentId: number;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
            /** Founderaddress */
            founderAddress: string;
            /** Vaultaddress */
            vaultAddress: string;
            /** Tokenaddress */
            tokenAddress: string;
            phase: components["schemas"]["AgentPhase"];
            /** Incubationstart */
            incubationStart: number;
            /** Publiclaunchat */
            publicLaunchAt?: number | null;
            /** Navusdc */
            navUsdc: string;
            /** Navpershareusdc */
            navPerShareUsdc: string;
            /** Totalshares */
            totalShares: string;
            /** Holdercount */
            holderCount: number;
            /** Apy30Dbps */
            apy30DBps?: number | null;
            /** Apy7Dbps */
            apy7DBps?: number | null;
            /** Reputation */
            reputation: number;
            /** Strategy */
            strategy: string;
            /** Assetclasses */
            assetClasses: components["schemas"]["AssetClass"][];
            /** Allowedlockups */
            allowedLockups: components["schemas"]["LockupTier"][];
            /** Thumbnailurl */
            thumbnailUrl?: string | null;
            /** Createdat */
            createdAt: number;
            performance?: components["schemas"]["AgentPerformance"] | null;
            /** Marketpricepershareusdc */
            marketPricePerShareUsdc?: string | null;
            /** Reputationpremiumbps */
            reputationPremiumBps?: number | null;
        };
        /** ApiError */
        ApiError: {
            error: components["schemas"]["ApiErrorCode"];
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ApiErrorCode
         * @enum {string}
         */
        ApiErrorCode: "BadRequest" | "NotFound" | "RateLimited" | "MandateParseFailed" | "MandateValidationFailed" | "ChainUnreachable" | "InternalError";
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "crypto" | "equity" | "treasury" | "cash" | "mixed";
        /** BenchmarkPoint */
        BenchmarkPoint: {
            /** Timestamp */
            timestamp: number;
            /** Agent */
            agent: number;
            /** Sspy */
            sspy: number;
            /** Sixtyforty */
            sixtyForty: number;
        };
        /** BenchmarkResponse */
        BenchmarkResponse: {
            /** Agentid */
            agentId: number;
            /** Periodstart */
            periodStart?: number | null;
            /** Periodend */
            periodEnd?: number | null;
            /** Samplecount */
            sampleCount: number;
            /** Series */
            series: components["schemas"]["BenchmarkPoint"][];
            summary?: components["schemas"]["BenchmarkSummary"] | null;
        };
        /** BenchmarkSummary */
        BenchmarkSummary: {
            /** Agentreturn */
            agentReturn: number;
            /** Sspyreturn */
            sspyReturn: number;
            /** Sixtyfortyreturn */
            sixtyFortyReturn: number;
            /** Alphavssspy */
            alphaVsSspy: number;
            /** Alphavssixtyforty */
            alphaVsSixtyForty: number;
        };
        /** ConditionCheckResponse */
        ConditionCheckResponse: {
            /** Agentid */
            agentId: number;
            /** Anytriggered */
            anyTriggered: boolean;
            /** Conditions */
            conditions: components["schemas"]["ConditionResult"][];
        };
        /** ConditionResult */
        ConditionResult: {
            /** Condition */
            condition: string;
            /** Parsed */
            parsed: boolean;
            /** Currentvalue */
            currentValue?: number | null;
            /** Threshold */
            threshold?: number | null;
            /** Triggered */
            triggered: boolean;
            /** Note */
            note?: string | null;
        };
        /** ContractAddresses */
        ContractAddresses: {
            /** Helmregistry */
            helmRegistry: string;
            /** Platformtreasury */
            platformTreasury: string;
            /** Redemptionqueue */
            redemptionQueue: string;
            /** Yieldharvester */
            yieldHarvester: string;
            /** Dividenddistributor */
            dividendDistributor: string;
            /** Pythpriceadapter */
            pythPriceAdapter: string;
            /** Mantlemethadapter */
            mantleMethAdapter: string;
            /** Ondousdyadapter */
            ondoUsdyAdapter: string;
            /** Pyth */
            pyth: string;
            /** Usdc */
            usdc: string;
            /** Agentnft */
            agentNft: string;
            /** Timeprovider */
            timeProvider: string;
            /** Agenttokenimpl */
            agentTokenImpl: string;
            /** Agentvaultimpl */
            agentVaultImpl: string;
            /** Foundervaultimpl */
            founderVaultImpl: string;
        };
        /** CronHealth */
        CronHealth: {
            /** Lastharvestrun */
            lastHarvestRun: number;
            /** Lastdividendrun */
            lastDividendRun: number;
            /** Healthy */
            healthy: boolean;
        };
        /** Decision */
        Decision: {
            /** Id */
            id: string;
            type: components["schemas"]["DecisionType"];
            /** Timestamp */
            timestamp: number;
            /** Txhash */
            txHash: string;
            /** Blocknumber */
            blockNumber: number;
            /** Summary */
            summary: string;
            /** Beforepositions */
            beforePositions?: components["schemas"]["Position"][] | null;
            /** Afterpositions */
            afterPositions?: components["schemas"]["Position"][] | null;
            /** Navbefore */
            navBefore?: string | null;
            /** Navafter */
            navAfter?: string | null;
            /** Harvestedusdc */
            harvestedUsdc?: string | null;
            /** Harvestedfromsources */
            harvestedFromSources?: components["schemas"]["HarvestSource"][] | null;
            /** Distributedepoch */
            distributedEpoch?: number | null;
            /** Distributedholdersusdc */
            distributedHoldersUsdc?: string | null;
            /** Distributedcarryusdc */
            distributedCarryUsdc?: string | null;
        };
        /**
         * DecisionType
         * @enum {string}
         */
        DecisionType: "Rebalance" | "Harvest" | "Distribute" | "WindDown";
        /** DividendClaim */
        DividendClaim: {
            /** Agentid */
            agentId: number;
            /** Agentname */
            agentName: string;
            /** Ticker */
            ticker: string;
            /** Claimableepochs */
            claimableEpochs: number[];
            /** Claimableamountusdc */
            claimableAmountUsdc: string;
            /** Oldestepochat */
            oldestEpochAt: number;
        };
        /** DividendEpoch */
        DividendEpoch: {
            /** Epoch */
            epoch: number;
            /** Agentid */
            agentId: number;
            /** Totalamountusdc */
            totalAmountUsdc: string;
            /** Holdersshareusdc */
            holdersShareUsdc: string;
            /** Carryshareusdc */
            carryShareUsdc: string;
            /** Distributedat */
            distributedAt: number;
            /** Totalsharesatsnapshot */
            totalSharesAtSnapshot: string;
        };
        /** FeeRates */
        FeeRates: {
            /** Mintbps */
            mintBps: number;
            /** Redeembps */
            redeemBps: number;
            /** Rebalancebps */
            rebalanceBps: number;
        };
        /** FounderVaultPosition */
        FounderVaultPosition: {
            /** Agentid */
            agentId: number;
            /** Agentname */
            agentName: string;
            /** Vaultaddress */
            vaultAddress: string;
            /** Foundervaultaddress */
            founderVaultAddress: string;
            /** Shareslocked */
            sharesLocked: string;
            /** Lockupendsat */
            lockupEndsAt: number;
            /** Carrybalanceusdc */
            carryBalanceUsdc: string;
            /** Cumulativewithdrawnbps */
            cumulativeWithdrawnBps: number;
            /** Issubordinationactive */
            isSubordinationActive: boolean;
        };
        /**
         * FounderVaultSnapshot
         * @description Embedded inside AgentDetail. (Distinct from full FounderVaultPosition in Portfolio.)
         */
        FounderVaultSnapshot: {
            /** Address */
            address: string;
            /** Sharesheld */
            sharesHeld: string;
            /** Lockupendsat */
            lockupEndsAt: number;
            /** Cumulativewithdrawnbps */
            cumulativeWithdrawnBps: number;
            /** Issubordinationactive */
            isSubordinationActive: boolean;
            /** Carrybalanceusdc */
            carryBalanceUsdc: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarvestSource */
        HarvestSource: {
            /** Source */
            source: string;
            /** Amount */
            amount: string;
        };
        /** HealthResponse */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            indexer: components["schemas"]["IndexerHealth"];
            cron: components["schemas"]["CronHealth"];
            llm: components["schemas"]["LlmHealth"];
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "ok" | "degraded" | "down";
        /** IndexerHealth */
        IndexerHealth: {
            /** Lastsyncedblock */
            lastSyncedBlock: number;
            /** Blocksbehind */
            blocksBehind: number;
            /** Healthy */
            healthy: boolean;
        };
        /** LlmHealth */
        LlmHealth: {
            /** Lastcallat */
            lastCallAt: number;
            /** Last24Hsuccessrate */
            last24HSuccessRate: number;
            /** Healthy */
            healthy: boolean;
        };
        /**
         * LockupTier
         * @enum {string}
         */
        LockupTier: "instant" | "30d" | "60d" | "90d";
        /** MandateParseRequest */
        MandateParseRequest: {
            /** Naturallanguagemandate */
            naturalLanguageMandate: string;
            /** Hints */
            hints?: {
                [key: string]: unknown;
            } | null;
        };
        /** MandateParseResponse */
        MandateParseResponse: {
            mandate: components["schemas"]["MandateSchema"];
            /** Mandatehash */
            mandateHash: string;
            /** Mandateuri */
            mandateUri: string;
            /** Warnings */
            warnings: string[];
        };
        /** MandateSchema */
        MandateSchema: {
            /**
             * Version
             * @constant
             */
            version: "1.0";
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
            /** Description */
            description: string;
            /** Assetclasses */
            assetClasses: components["schemas"]["AssetClass"][];
            /** Targetuniverse */
            targetUniverse: string[];
            /** Weightconstraints */
            weightConstraints: components["schemas"]["WeightConstraint"][];
            /**
             * Rebalancefrequency
             * @enum {string}
             */
            rebalanceFrequency: "daily" | "weekly" | "monthly" | "event-driven";
            /** Rebalancetriggers */
            rebalanceTriggers: string[];
            /** Allowedlockups */
            allowedLockups: components["schemas"]["LockupTier"][];
            /** Minimumdepositusdc */
            minimumDepositUsdc: string;
            /** Foundersharebps */
            founderShareBps: number;
            /** Carrybps */
            carryBps: number;
            /** Founderlockupdays */
            founderLockupDays: number;
            /** Subordinationthresholdbps */
            subordinationThresholdBps: number;
            /** Maxleverage */
            maxLeverage: number;
            /** Maxsinglepositionbps */
            maxSinglePositionBps: number;
            /** Emergencyexitconditions */
            emergencyExitConditions: string[];
            /** Expectedyieldapy */
            expectedYieldAPY?: string | null;
            /** Personalityhint */
            personalityHint?: string | null;
        };
        /** MandateValidateRequest */
        MandateValidateRequest: {
            mandate: components["schemas"]["MandateSchema"];
        };
        /** MandateValidateResponse */
        MandateValidateResponse: {
            /** Valid */
            valid: boolean;
            /** Errors */
            errors: string[];
            /** Hash */
            hash?: string | null;
        };
        /** MintPreviewRequest */
        MintPreviewRequest: {
            /** Amountusdc */
            amountUsdc: string;
        };
        /** MintPreviewResponse */
        MintPreviewResponse: {
            /** Amountusdc */
            amountUsdc: string;
            /** Shares */
            shares: string;
            /** Navatpreview */
            navAtPreview: string;
            /** Platformfeeusdc */
            platformFeeUsdc: string;
            /** Pythfeemntwei */
            pythFeeMntWei: string;
            /** Validuntil */
            validUntil: number;
            /** Syntheticprices */
            syntheticPrices: components["schemas"]["SyntheticPricePreview"][];
        };
        /** MintUsdcRequest */
        MintUsdcRequest: {
            /** To */
            to: string;
            /** Amountusdc */
            amountUsdc: string;
        };
        /** MintUsdcResponse */
        MintUsdcResponse: {
            /** Txhash */
            txHash: string;
            /** To */
            to: string;
            /** Amountusdc */
            amountUsdc: string;
        };
        /** NarratorNote */
        NarratorNote: {
            /** Generatedat */
            generatedAt: number;
            /** Weekstart */
            weekStart: number;
            /** Weekend */
            weekEnd: number;
            /** Bodymarkdown */
            bodyMarkdown: string;
            performance: components["schemas"]["NarratorPerformance"];
        };
        /** NarratorPerformance */
        NarratorPerformance: {
            /** Navstart */
            navStart: string;
            /** Navend */
            navEnd: string;
            /** Returnbps */
            returnBps: number;
        };
        /**
         * NavGranularity
         * @enum {string}
         */
        NavGranularity: "minute" | "hour" | "day";
        /** NavHistoryResponse */
        NavHistoryResponse: {
            /** Points */
            points: components["schemas"]["NavPoint"][];
            period: components["schemas"]["NavPeriod"];
            granularity: components["schemas"]["NavGranularity"];
        };
        /**
         * NavPeriod
         * @enum {string}
         */
        NavPeriod: "24h" | "7d" | "30d" | "all";
        /** NavPoint */
        NavPoint: {
            /** Timestamp */
            timestamp: number;
            /** Navusdc */
            navUsdc: string;
            /** Navpershareusdc */
            navPerShareUsdc: string;
            /** Totalshares */
            totalShares: string;
        };
        /** Page[AgentSummary] */
        Page_AgentSummary_: {
            /** Items */
            items: components["schemas"]["AgentSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Decision] */
        Page_Decision_: {
            /** Items */
            items: components["schemas"]["Decision"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PortfolioPosition */
        PortfolioPosition: {
            /** Agentid */
            agentId: number;
            /** Agentname */
            agentName: string;
            /** Ticker */
            ticker: string;
            /** Vaultaddress */
            vaultAddress: string;
            /** Tokenaddress */
            tokenAddress: string;
            /** Shares */
            shares: string;
            /** Weightbps */
            weightBps: number;
            /** Valueusdc */
            valueUsdc: string;
            /** Costbasisusdc */
            costBasisUsdc?: string | null;
            /** Unrealizedpnlusdc */
            unrealizedPnlUsdc?: string | null;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Totalvalueusdc */
            totalValueUsdc: string;
            /** Positions */
            positions: components["schemas"]["PortfolioPosition"][];
            /** Pendingdividends */
            pendingDividends: components["schemas"]["DividendClaim"][];
            /** Pendingredemptions */
            pendingRedemptions: components["schemas"]["RedemptionRequest"][];
            /** Foundervaults */
            founderVaults: components["schemas"]["FounderVaultPosition"][];
        };
        /** Position */
        Position: {
            /** Asset */
            asset: string;
            /** Symbol */
            symbol: string;
            assetClass: components["schemas"]["AssetClass"];
            /** Amount */
            amount: string;
            /** Valueusdc */
            valueUsdc: string;
            /** Weightbps */
            weightBps: number;
            /** Priceusdc */
            priceUsdc?: string | null;
            /** Priceupdatedat */
            priceUpdatedAt?: number | null;
            /** Pricestale */
            priceStale?: boolean | null;
        };
        /** PythUpdateBytesResponse */
        PythUpdateBytesResponse: {
            /** Updatedata */
            updateData: string[];
            /** Feemntwei */
            feeMntWei: string;
            /** Feeds */
            feeds: string[];
            /** Fetchedat */
            fetchedAt: number;
        };
        /** QualificationCriterion */
        QualificationCriterion: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Passed */
            passed: boolean;
            /** Actual */
            actual: string;
            /** Threshold */
            threshold: string;
            /** Note */
            note?: string | null;
        };
        /** QualificationResponse */
        QualificationResponse: {
            /** Agentid */
            agentId: number;
            /** Overallpassed */
            overallPassed: boolean;
            /** Checks */
            checks: components["schemas"]["QualificationCriterion"][];
            /** Advanced */
            advanced: boolean;
            /** Txhash */
            txHash?: string | null;
            /** Newphase */
            newPhase?: string | null;
        };
        /** RedemptionQueueSnapshot */
        RedemptionQueueSnapshot: {
            /** Pendingshares */
            pendingShares: string;
            /** Requestcount */
            requestCount: number;
            /** Nextunlockat */
            nextUnlockAt?: number | null;
        };
        /** RedemptionRequest */
        RedemptionRequest: {
            /** Requestid */
            requestId: number;
            /** Agentid */
            agentId: number;
            /** Agentname */
            agentName: string;
            /** Shares */
            shares: string;
            tier: components["schemas"]["LockupTier"];
            /** Unlockat */
            unlockAt: number;
            /** Estimatedusdc */
            estimatedUsdc: string;
            status: components["schemas"]["RedemptionStatus"];
        };
        /**
         * RedemptionStatus
         * @enum {string}
         */
        RedemptionStatus: "Pending" | "Claimable" | "Claimed" | "Cancelled";
        /** SyntheticAssetInfo */
        SyntheticAssetInfo: {
            /** Address */
            address: string;
            /** Symbol */
            symbol: string;
            /** Underlying */
            underlying: string;
            /** Pythfeedid */
            pythFeedId: string;
        };
        /** SyntheticPricePreview */
        SyntheticPricePreview: {
            /** Symbol */
            symbol: string;
            /** Priceusdc */
            priceUsdc: string;
            /** Pythconfidence */
            pythConfidence: string;
            /** Freshat */
            freshAt: number;
        };
        /** SystemInfo */
        SystemInfo: {
            /** Chainid */
            chainId: number;
            /** Rpcurl */
            rpcUrl: string;
            /** Blockexplorerurl */
            blockExplorerUrl: string;
            contracts: components["schemas"]["ContractAddresses"];
            feeRates: components["schemas"]["FeeRates"];
            /** Pythfeedids */
            pythFeedIds: {
                [key: string]: string;
            };
            /** Syntheticassets */
            syntheticAssets: components["schemas"]["SyntheticAssetInfo"][];
        };
        /** TimeAdvanceRequest */
        TimeAdvanceRequest: {
            /** Seconds */
            seconds: number;
        };
        /** TimeAdvanceResponse */
        TimeAdvanceResponse: {
            /** Txhash */
            txHash: string;
            /** Advancedseconds */
            advancedSeconds: number;
            /** Newcurrenttime */
            newCurrentTime: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightConstraint */
        WeightConstraint: {
            /** Asset */
            asset: string;
            /** Minbps */
            minBps: number;
            /** Maxbps */
            maxBps: number;
        };
        /** WindDownState */
        WindDownState: {
            /** Triggeredat */
            triggeredAt: number;
            /** Triggeredby */
            triggeredBy: string;
            /** Reason */
            reason: string;
            /** Positionsremaining */
            positionsRemaining: number;
            /** Estimatedsettleat */
            estimatedSettleAt: number;
            /** Seniorclaimableusdc */
            seniorClaimableUsdc: string;
            /** Juniorclaimableusdc */
            juniorClaimableUsdc: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_agents_get: {
        parameters: {
            query?: {
                phase?: components["schemas"]["AgentPhase"][] | null;
                assetClass?: components["schemas"]["AssetClass"][] | null;
                lockup?: components["schemas"]["LockupTier"][] | null;
                /** @description apy_30d|apy_7d|nav|holders|newest|created_at|reputation|sharpe|total_return|max_drawdown */
                sort?: string;
                /** @description asc|desc */
                order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AgentSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nav_history_agents__agent_id__nav_history_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["NavPeriod"];
                granularity?: components["schemas"]["NavGranularity"] | null;
            };
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavHistoryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_benchmark_agents__agent_id__benchmark_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conditions_agents__agent_id__conditions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionCheckResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_decisions_agents__agent_id__decisions_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["DecisionType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Decision_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_preview_agents__agent_id__mint_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MintPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MintPreviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    pyth_update_bytes_agents__agent_id__pyth_update_bytes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PythUpdateBytesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    parse_mandate_mandate_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MandateParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateParseResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    validate_mandate_mandate_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MandateValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_portfolio__address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_redemptions_redemptions__address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedemptionRequest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_info_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    admin_time_advance_admin_time_advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeAdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeAdvanceResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    admin_mint_usdc_admin_mint_usdc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MintUsdcRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MintUsdcResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    admin_rebalance_admin_agents__agent_id__rebalance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRebalanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    admin_harvest_admin_agents__agent_id__harvest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHarvestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    admin_distribute_admin_agents__agent_id__distribute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDistributeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    admin_nft_metadata_admin_agents__agent_id__nft_metadata_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNftMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    debug_indexer_state_admin_debug_indexer_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debug_agent_compare_admin_debug_agents__agent_id__compare_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_synthetic_prices_admin_debug_synthetic_prices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debug_adapters_admin_debug_adapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debug_treasury_admin_debug_treasury_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debug_founder_vault_admin_debug_agents__agent_id__founder_vault_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_redemption_queue_admin_debug_agents__agent_id__redemption_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_qualify_check_admin_agents__agent_id__qualify_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualificationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    admin_qualify_advance_admin_agents__agent_id__qualify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualificationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    system_health_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
