/**
 * Helm Backend API client.
 *
 * Types come from src/lib/api-types.gen.ts (auto-generated by openapi-typescript).
 * Regenerate with `pnpm gen:api` after any BE deploy.
 *
 * Usage:
 *   import { api } from "@/lib/api";
 *   const data = await api.get("/agents", { query: { limit: 20 } });
 */

import type { paths } from "@/lib/api-types.gen";
import { env } from "@/lib/env";

export class ApiError extends Error {
  constructor(
    public status: number,
    public detail: unknown,
    message?: string,
  ) {
    super(message ?? `API error ${status}`);
    this.name = "ApiError";
  }
}

type Method = "get" | "post" | "put" | "delete" | "patch";

// Narrow helpers so the call site stays type-safe.
type PathsOf<M extends Method> = {
  [P in keyof paths]: paths[P] extends { [K in M]: unknown } ? P : never;
}[keyof paths];

type Op<P extends keyof paths, M extends Method> = paths[P] extends {
  [K in M]: infer O;
}
  ? O
  : never;

type Params<P extends keyof paths, M extends Method> = Op<P, M> extends {
  parameters: infer X;
}
  ? X
  : never;

type RequestBody<P extends keyof paths, M extends Method> = Op<
  P,
  M
> extends {
  requestBody?: { content: { "application/json": infer B } };
}
  ? B
  : never;

type Success<P extends keyof paths, M extends Method> = Op<P, M> extends {
  responses: { 200: { content: { "application/json": infer R } } };
}
  ? R
  : never;

/**
 * Substitute {param} placeholders in path with values from `path` params.
 */
function buildUrl(
  path: string,
  params: { path?: Record<string, unknown>; query?: Record<string, unknown> },
): string {
  let url = path;
  if (params.path) {
    for (const [k, v] of Object.entries(params.path)) {
      url = url.replace(`{${k}}`, encodeURIComponent(String(v)));
    }
  }
  const qs = new URLSearchParams();
  if (params.query) {
    for (const [k, v] of Object.entries(params.query)) {
      if (v === undefined || v === null) continue;
      if (Array.isArray(v)) {
        for (const item of v) qs.append(k, String(item));
      } else {
        qs.set(k, String(v));
      }
    }
  }
  const q = qs.toString();
  return `${env.apiUrl}${url}${q ? `?${q}` : ""}`;
}

async function request<R>(
  method: string,
  url: string,
  body?: unknown,
): Promise<R> {
  const r = await fetch(url, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
    cache: "no-store", // BE-level cache headers govern; FE never persists.
  });
  if (!r.ok) {
    let detail: unknown = null;
    try {
      detail = await r.json();
    } catch {
      detail = await r.text().catch(() => null);
    }
    throw new ApiError(r.status, detail);
  }
  // 204 No Content guard
  if (r.status === 204) return undefined as R;
  return (await r.json()) as R;
}

export const api = {
  async get<P extends PathsOf<"get">>(
    path: P,
    params?: Params<P, "get">,
  ): Promise<Success<P, "get">> {
    const url = buildUrl(path as string, (params as never) ?? {});
    return request<Success<P, "get">>("GET", url);
  },

  async post<P extends PathsOf<"post">>(
    path: P,
    body?: RequestBody<P, "post">,
    params?: Params<P, "post">,
  ): Promise<Success<P, "post">> {
    const url = buildUrl(path as string, (params as never) ?? {});
    return request<Success<P, "post">>("POST", url, body);
  },
};
